config/routes.rb
Rails.application.routes.draw do

  resources :pembobotans

  resources :minats

  resources :kehidupan_perasaans

  resources :sikap_kerjas

  resources :kecerdasans

  resources :siswas do
    member do
      get 'psikotest'
      get 'hasil'
      get 'pencabangan'
      get 'laporan'
    end

  end

  devise_for :users

  root 'dashboard#index'

    get 'laporan' => 'siswas#laporan'

end

app/models/siswa.rb
class Siswa < ActiveRecord::Base
  self.table_name = 'siswa'
  self.primary_key = 'id_csiswa'

  validates :nama_lengkap, :tempat_lahir, :tanggal_lahir, :tg_badan, :b_badan, :agama, :pendidikan, :minat_kec, presence: true

  has_one :kecerdasan, primary_key: :id_csiswa, foreign_key: :id_csiswa
  has_one :kehidupan_perasaan, primary_key: :id_csiswa, foreign_key: :id_csiswa
  has_one :sikap_kerja, primary_key: :id_csiswa, foreign_key: :id_csiswa
  has_one :minat, primary_key: :id_csiswa, foreign_key: :id_csiswa

  after_create :init_childs
  accepts_nested_attributes_for :kecerdasan
  accepts_nested_attributes_for :kehidupan_perasaan
  accepts_nested_attributes_for :sikap_kerja
  accepts_nested_attributes_for :minat  

  before_save :init_usia
  before_update :set_rekomendasi_kecabangan


  def init_usia
    begin
      self.usia = (Date.today - self.tanggal_lahir.to_date).to_i / 356
      self.tgl_pendaftaran = Date.today
    rescue
    end
  end

  def init_childs
    Kecerdasan.create(id_csiswa: self.id)
    KehidupanPerasaan.create(id_csiswa: self.id)
    SikapKerja.create(id_csiswa: self.id)
    Minat.create(id_csiswa: self.id)
  end       

  def set_rekomendasi_kecabangan
    if kecerdasan.pemahaman
      rests = Pembobotan.pluck(:pencabangan).uniq
      arr = []
      selected_rec = nil
      tmp_arr = []
      rests.each do |res|
        new_arr = [kecerdasan.nilai(res), sikap_kerja.nilai(res), kehidupan_perasaan.nilai(res), minat.nilai(res)]
        if(tmp_arr.blank? && selected_rec.blank?)
          selected_rec = res
          tmp_arr = new_arr
        elsif((tmp_arr <=> new_arr) == -1)
          selected_rec = res
          tmp_arr = new_arr
        end

      end
      self.rekomendasi_kecabangan = selected_rec  #this is indicate that siswa already input their numbers
    end
  end  


end

app/controllers/siswas_controller.rb
class SiswasController < ApplicationController
  before_action :set_siswa, only: [:show, :edit, :update, :destroy, :psikotest, :hasil, :pencabangan]

  respond_to :html

  def index
    if request.xhr?
      @q = Siswa.ransack(params[:q])
      @siswas = @q.result(distinct: true)
      render layout: false 
    end
  end

  def show
    @siswa.tanggal_lahir = @siswa.tanggal_lahir.strftime("%d-%m-%Y")
    respond_with(@siswa)
  end

  def pencabangan
    render layout: false if request.xhr?
  end
  
  def psikotest
    render layout: false if request.xhr?

  end

  def hasil
    if request.xhr?
      par = params[:pencabangan] || "INF"
      @minat = @siswa.minat.hasil_pembobotan(par)
      @kecerdasan = @siswa.kecerdasan.hasil_pembobotan(par)
      @kehidupan_perasaan = @siswa.kehidupan_perasaan.hasil_pembobotan(par)
      @sikap_kerja = @siswa.sikap_kerja.hasil_pembobotan(par)
      render layout: false
    end
  end

  def new
    @siswa = Siswa.new
    @siswa.id_csiswa = Siswa.last.try(:id_csiswa).to_i + 1
    respond_with(@siswa)
  end

  def edit
    @siswa.tgl_pendaftaran = @siswa.tgl_lahir.strftime("%d-%m-%Y")
  end

  def laporan
    if params[:id]
      @siswa = Siswa.find_by(id_csiswa: params[:id])
      render pdf: "laporan_siswa", layout: false,:margin => { :bottom => 20 }
    else
      @siswas = Siswa.all
      render pdf: "laporan_keseluruhan_siswa", layout: false,:margin => { :bottom => 20 }
    end
  end

  def create
    @siswa = Siswa.new(siswa_params)
    @siswa.id = Siswa.last.try(:id).to_i + 1
    
    if @siswa.save
      flash[:notice] = "Data berhasil disimpan."
      redirect_to siswas_path
    else
      redirect_to :back, notice: "Data gagal disimpan, periksa kembali inputan."
    end
  end

  def update
    if @siswa.update(siswa_params)
      flash[:notice] = "Data berhasil disimpan."
      redirect_to (request.referer.include?('psikotest') ? psikotest_siswa_path(@siswa) : siswas_path)
    else
      redirect_to :back, notice: "Data gagal disimpan, periksa kembali inputan."
    end
    # respond_with(@siswa)
  end

  def destroy
    @siswa.destroy
    respond_with(@siswa)
  end

  private
    def set_siswa
      @siswa = Siswa.find_by(id_csiswa: params[:id])
    end

    def siswa_params
      params.require(:siswa).permit!
    end
end

app/helpers/siswas_helper.rb
module SiswasHelper
end

app/views/siswas/_hasil_blank.html.erb
   <select class="form-control" onchange="changeHasilTipe()">
        <option>- SILAKAN PILIH PENCABANGAN -</option>
        <% Pembobotan.pluck(:pencabangan).uniq.each do |pemb| %>
          <option value="<%= pemb %>" <%= "selected" if pemb.eql?(params[:pencabangan]) %> ><%= pemb %></option>
        <% end %>
      </select>
      <h3>Kecerdasan</h3>
      <table class="table table-bordered table-stripped">
        <tr>
          <th>Pemahaman</th>
          <th>Mengingat</th>
          <th>Analisa</th>
          <th>Konstruktif</th>
          </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          </tr>
        <tr>
        <th>Mengolah Angka</th>
          <th>Aritmatika</th>
          <th>Orientasi Ruang</th>
          <th>Verbal</th>
        </tr>
        <tr>  
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        </tr>
        <tr>
        <th>Estimasi</th>
          <th>Tehnik Mekanik</th>
          <th>Tehnik Elektronik</th>
          <th>Wawasan</th>
        </tr>

          
          
          
        <tr>  
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </table>
      <h3>Sikap Kerja</h3>
      <table class="table table-bordered table-stripped">
        <tr>
          <th>Inisiatif</th>
          <th>Kreatif</th>
          <th>Perencanaan</th>
          <th>Energi</th>
          
          </tr>
        <tr>
          <td></td>

          <td></td>

          <td></td>
          <td></td>
          
          </tr>
        <tr>
          <th>Kecepatan</th>
          <th>Ketelitian</th>
          <th>Ketekunan</th>
          <th>Keuletan</th>
           
        </tr>
        <tr>  
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          
        </tr>
        <tr>
          <th>Konsentrasi</th>   
          <th>Daya Tahan</th>
          <th>Kepemimpinan</th>
          <th>Kerjasama</th>
        </tr>
          
        <tr>  
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th colspan="4">Toleransi Terhadap Stress</th>
        </tr>
          
        <tr>  
          <td  colspan="4"></td>
        </tr>

      </table>
      <h3>Kehidupan Perasaan</h3>
      <table class="table table-bordered table-stripped">
        <tr>
          <th>Kepekaan</th>
          <th>Penempatan Diri</th>
          <th>Kepercayaan Diri</th>
          <th>Kemandirian</th>
          </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          </tr>
        <tr>
          <th>Persuasif</th>
          <th>Agresivitas</th>
          <th>Pengelolaan Dorongan</th>
          <th>Pengelolaan Emosi</th>
        </tr>
        <tr>    
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>  
      </table>
      <h3>Minat</h3>
      <table class="table table-bordered table-stripped">
        <tr>
          <th>Alam Terbuka</th>
          <th>Seni</th>
          <th>Pelayanan Sosial</th>
          <th>Klerical</th>
          </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          
          </tr>
        <tr>
        <th>Teknik Mekanik</th>
          <th>Hitungan</th>
          <th>Kepustakaan</th>
          <th>Ilmiah Sain</th>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          
        </tr>
      </table>
    

app/views/siswas/_laporan_individu.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  
  <title>SISTEM PENDUKUNG KEPUTUSAN PENEMPATAN KECABANGAN TNI AD</title>

  <!-- Bootstrap Core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link href="/assets/print.css" rel="stylesheet" media="print">
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper">

    <div id="page-wrapper" >
      <div class="col-sm-12">

        <img src="https://scontent-lga3-1.cdninstagram.com/t51.2885-15/e35/18514068_1368599536519015_2340271063331504128_n.jpg" class="img-rounded" width="80px" height="80px" style="float: left;margin-right: 10px">
        <h4 style="padding-top: 30px;">SISTEM PENDUKUNG KEPUTUSAN PENEMPATAN KECABANGAN TNI AD</h4>
      </div>
      <div class="clearfix"></div>
      <br>
      <h4> Data Siswa </h4>
      <table class="table borderless">
        <tr>
          <th>
            ID Calon Siswa
          </th>
          <td>
            <%= text_field_tag "field", @siswa.id_csiswa, class: "form-control input-sm" %>
          </td>
          <th>
            Minat Kecabangan
          </th>
          <td>
            <%= text_field_tag "field", @siswa.minat_kec, class: "form-control input-sm" %>
          </td>
        </tr>
        <tr>
          <th>
            Nama Lengkap
          </th>
          <td>
            <%= text_field_tag "field", @siswa.nama_lengkap, class: "form-control input-sm" %>
          </td>
          <th>
            Rekomendasi Kecabangan
          </th>
          <td>
            <%= text_field_tag "field", @siswa.rekomendasi_kecabangan, class: "form-control input-sm" %>
          </td>
        </tr>
        <tr>
          <th>
            Tempat Lahir
          </th>
          <td>
            <%= text_field_tag "field", @siswa.tempat_lahir, class: "form-control input-sm" %>
          </td>
          <th>
            Tanggal Lahir
          </th>
          <td>
            <%= text_field_tag "field", @siswa.tanggal_lahir.strftime("%d-%m-%Y"), class: "form-control input-sm" %>
          </td>
        </tr>  
        <tr>
          <th>
            Tinggi Badan
          </th>
          <td>
            <%= text_field_tag "field", @siswa.tg_badan, class: "form-control input-sm" %>
          </td>
          <th>
            Berat Badan
          </th>
          <td>
            <%= text_field_tag "field", @siswa.b_badan, class: "form-control input-sm" %>
          </td>
        </tr>  
        <tr>
          <th>
            Usia
          </th>
          <td>
            <%= text_field_tag "field", @siswa.usia, class: "form-control input-sm" %>
          </td>
          <th>

          </th>
          <td>

          </td>
        </tr>  
        <tr>
          <th>
            Agama
          </th>
          <td>
            <%= text_field_tag "field", @siswa.agama, class: "form-control input-sm" %>
          </td>
          <th>

          </th>
          <td>

          </td>
        </tr>  
        <tr>
          <th>
            Riwayat Pendidikan
          </th>
          <td>
            <%= text_field_tag "field", @siswa.pendidikan, class: "form-control input-sm" %>
          </td>
          <th>

          </th>
          <td>

          </td>
        </tr>  
      </table>

      <h4> Kecerdasan </h4>

      <table class="table table-bordered table-stripped table-custom">
        <tr>
          <th>Pemahaman</th>
          <th>Mengingat</th>
          <th>Analisa</th>
          <th>Konstruktif</th>
          </tr>
        <tr>
          <td><%= @siswa.kecerdasan.pemahaman %></td>
          <td><%= @siswa.kecerdasan.mengingat %></td>
          <td><%= @siswa.kecerdasan.analisa %></td>
          <td><%= @siswa.kecerdasan.konstruktif %></td>
          </tr>
        <tr>
        <th>Mengolah Angka</th>
          <th>Aritmatika</th>
          <th>Orientasi Ruang</th>
          <th>Verbal</th>
        </tr>
        <tr>  
        <td><%= @siswa.kecerdasan.mengolah_angka %></td>
          <td><%= @siswa.kecerdasan.aritmatika %></td>
          <td><%= @siswa.kecerdasan.orientasi_ruang %></td>
          <td><%= @siswa.kecerdasan.verbal %></td>
        </tr>
        <tr>
        <th>Estimasi</th>
          <th>Tehnik Mekanik</th>
          <th>Tehnik Elektronik</th>
          <th>Wawasan</th>
        </tr>

          
          
          
        <tr>  
          <td><%= @siswa.kecerdasan.estimasi %></td>
          <td><%= @siswa.kecerdasan.tehnik_mekanik %></td>
          <td><%= @siswa.kecerdasan.tehnik_elektronik %></td>
          <td><%= @siswa.kecerdasan.wawasan %></td>
        </tr>
      </table>

      <h3>Sikap Kerja</h3>
      <table class="table table-bordered table-stripped">
        <tr>
          <th>Inisiatif</th>
          <th>Kreatif</th>
          <th>Perencanaan</th>
          <th>Energi</th>
          
          </tr>
        <tr>
          <td><%= @siswa.sikap_kerja.inisiatif %></td>
          <td><%= @siswa.sikap_kerja.kreatif %></td>
          <td><%= @siswa.sikap_kerja.perencanaan %></td>
          <td><%= @siswa.sikap_kerja.energi %></td>
          
          </tr>
        <tr>
          <th>Kecepatan</th>
          <th>Ketelitian</th>
          <th>Ketekunan</th>
          <th>Keuletan</th>
           
        </tr>
        <tr>  
          <td><%= @siswa.sikap_kerja.kecepatan %></td>
          <td><%= @siswa.sikap_kerja.ketelitian %></td>
          <td><%= @siswa.sikap_kerja.ketekunan %></td>
          <td><%= @siswa.sikap_kerja.keuletan %></td>
          
        </tr>
        <tr>
          <th>Konsentrasi</th>   
          <th>Daya Tahan</th>
          <th>Kepemimpinan</th>
          <th>Kerjasama</th>
        </tr>
          
        <tr>  
          <td><%= @siswa.sikap_kerja.konsentrasi %></td>
          <td><%= @siswa.sikap_kerja.daya_tahan %></td>
          <td><%= @siswa.sikap_kerja.kepemimpinan %></td>
          <td><%= @siswa.sikap_kerja.kerjasama %></td>
        </tr>
        <tr>
          <th colspan="2">Toleransi Terhadap Stress</th>
        </tr>
          
        <tr>  
          <td  colspan="2"><%= @siswa.sikap_kerja.toleransi_terhadap_stress %></td>
        </tr>

      </table>

      <h3>Kehidupan Perasaan</h3>
      <table class="table table-bordered table-stripped">
        <tr>
          <th>Kepekaan</th>
          <th>Penempatan Diri</th>
          <th>Kepercayaan Diri</th>
          <th>Kemandirian</th>
          </tr>
        <tr>
          <td><%= @siswa.kehidupan_perasaan.kepekaan %></td>
          <td><%= @siswa.kehidupan_perasaan.penempatan_diri %></td>
          <td><%= @siswa.kehidupan_perasaan.kepercayaan_diri %></td>
          <td><%= @siswa.kehidupan_perasaan.kemandirian  %></td>
          </tr>
        <tr>
          <th>Persuasif</th>
          <th>Agresivitas</th>
          <th>Pengelolaan Dorongan</th>
          <th>Pengelolaan Emosi</th>
        </tr>
        <tr>    
          <td><%= @siswa.kehidupan_perasaan.persuasif %></td>
          <td><%= @siswa.kehidupan_perasaan.agresivitas %></td>
          <td><%= @siswa.kehidupan_perasaan.pengelolaan_dorongan %></td>
          <td><%= @siswa.kehidupan_perasaan.pengelolaan_emosi %></td>
        </tr>  
      </table>

      <h3>Minat</h3>
      <table class="table table-bordered table-stripped">
        <tr>
          <th>Alam Terbuka</th>
          <th>Seni</th>
          <th>Pelayanan Sosial</th>
          <th>Klerical</th>
          </tr>
        <tr>
          <td><%= @siswa.minat.alam_terbuka %></td>
          <td><%= @siswa.minat.seni %></td>
          <td><%= @siswa.minat.pelayanan_sosial %></td>
          <td><%= @siswa.minat.klerical %></td>
          </tr>
        <tr>
        <th>Teknik Mekanik</th>
          <th>Hitungan</th>
          <th>Kepustakaan</th>
          <th>Ilmiah Sain</th>
        </tr>
        <tr>
      <td><%= @siswa.minat.teknik_mekanik %></td>
          <td><%= @siswa.minat.hitungan %></td>
          <td><%= @siswa.minat.kepustakaan %></td>
          <td><%= @siswa.minat.ilmiah_sain %></td>
        </tr>
      </table>
    </div>
    <br><br><br>
    <div style="float: right">
      <p>Bandung, <%= Date.today.strftime("%d-%m-%Y") %></p>
      <p>Kalasiappsi</p>
      <br>
      <br>
      <br>
      <br>
      <p>Kolonel(CAJ) Drs. Gunawan, DESS</p>
    </div>
    <!-- /#page-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- jQuery -->

</body>

</html>

app/views/siswas/hasil.html.erb
<div class="col-sm-3 buttons">
  <%= link_to "Kelola Psikotest", psikotest_siswa_path(@siswa), class: "btn btn-default first-btn"%>
  <div class="clearfix"></div>
  <br>
  <%= link_to "Lihat Hasil", hasil_siswa_path(@siswa), class: "btn btn-primary"%>
  <div class="clearfix"></div>
  <br>
  <%= link_to "Rekomendasi Pencabangan", pencabangan_siswa_path(@siswa), class: "btn btn-default"%>
  <div class="clearfix"></div>
</div>

<div class="col-sm-9 psikotest-result">
   
</div>
<div class="clearfix"></div>
<br>


<% content_for :bottom_assets do %>
  <style type="text/css">
    .modal-dialog.modal-sm{
      margin: 200px auto;
    }
  </style>
  <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content" style="padding: 10px;text-align: center;">
        
        <br>
        <div class="progress">
          <div class="progress-bar progress-bar-striped active" role="progressbar"
          aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
            Data sedang diproses....
          </div>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $("document").ready(function(){
      $('.bs-example-modal-sm').modal()
      $.ajax({
          url: "<%= request.path %>.js",
          cache: false,
          success: function(html){
            $('.bs-example-modal-sm').modal('hide')            
          }
      });
    });  
    function changeHasilTipe(){
      $('.bs-example-modal-sm').modal()
      $.ajax({
          url: "/siswas/<%= @siswa.id %>/hasil.js?pencabangan=" + $("select").val(),
          cache: false,
          success: function(html){
            $('.bs-example-modal-sm').modal('hide')            
          }
      });
    }
  </script>
<% end %>

app/views/siswas/hasil.js.erb
$(".psikotest-result").html("<%= @siswa.minat.alam_terbuka ? escape_javascript(render 'hasil') : escape_javascript(render 'hasil_blank')%>"); 

app/views/siswas/index.html.erb
<div style="float:right">
<% if current_user.level.eql?(1) %>
<%= link_to "<i class='fa fa-user-plus fa-3x'></i>".html_safe, new_siswa_path, style: "margin-right:20px" %>
<% end %>
<%= link_to "<i class='fa fa-print fa-3x'></i>".html_safe, laporan_path %>
<br>
<br>
</div>
<div style="clear: both;"></div>

<div class="psikotest-result">
  
</div>


<% content_for :bottom_assets do %>
  <style type="text/css">
    .modal-dialog.modal-sm{
      margin: 200px auto;
    }
  </style>
  <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content" style="padding: 10px;text-align: center;">
        
        <br>
        <div class="progress">
          <div class="progress-bar progress-bar-striped active" role="progressbar"
          aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
            Data sedang diproses....
          </div>
        </div>
      </div>
    </div>
  </div>


  <script src="https://blackrockdigital.github.io/startbootstrap-sb-admin-2/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-sb-admin-2/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-sb-admin-2/vendor/datatables-responsive/dataTables.responsive.js"></script>

  <script type="text/javascript">
    $("document").ready(function(){
      $('.bs-example-modal-sm').modal()
      $.ajax({
          url: "<%= request.path %>.js",
          cache: false,
          success: function(html){
            $('.bs-example-modal-sm').modal('hide')            
            $('#dataTables-example').DataTable({
                responsive: true
            });
          }
      });
    });  
  </script>
    
<% end %>

app/views/siswas/index.js.erb
$(".psikotest-result").html("<%= escape_javascript(render 'index') %>"); 

app/views/siswas/laporan.html.erb
<%= render (@siswa ? "laporan_individu" : "laporan_keseluruhan") %>

app/views/siswas/new.html.erb
<%= render 'form' %>

app/views/siswas/pencabangan.html.erb
<div class="col-sm-3 buttons">
  <%= link_to "Kelola Psikotest", psikotest_siswa_path(@siswa), class: "btn btn-default first-btn"%>
  <div class="clearfix"></div>
  <br>
  <%= link_to "Lihat Hasil", hasil_siswa_path(@siswa), class: "btn btn-default" %>
  <div class="clearfix"></div>
  <br>
  <%= link_to "Rekomendasi Pencabangan", pencabangan_siswa_path(@siswa), class: "btn btn-primary"%>
  <div class="clearfix"></div>
</div>

<div class="col-sm-9 psikotest-result">
  
</div>


<% content_for :bottom_assets do %>
  <style type="text/css">
    .modal-dialog.modal-sm{
      margin: 200px auto;
    }
  </style>
  <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content" style="padding: 10px;text-align: center;">
        
        <br>
        <div class="progress">
          <div class="progress-bar progress-bar-striped active" role="progressbar"
          aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
            Data sedang diproses....
          </div>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $("document").ready(function(){
      $('.bs-example-modal-sm').modal()
      $.ajax({
          url: "<%= request.path %>.js",
          cache: false,
          success: function(html){
            $('.bs-example-modal-sm').modal('hide')            
          }
      });
    });  
  </script>
<% end %>

app/views/siswas/psikotest.html.erb
<div class="col-sm-3 buttons">
  <%= link_to "Kelola Psikotest", psikotest_siswa_path(@siswa), class: "btn btn-primary first-btn"%>
  <div class="clearfix"></div>
  <br>
  <%= link_to "Lihat Hasil", hasil_siswa_path(@siswa), class: "btn btn-default"%>
  <div class="clearfix"></div>
  <br>
  <%= link_to "Rekomendasi Pencabangan", pencabangan_siswa_path(@siswa), class: "btn btn-default"%>
  <div class="clearfix"></div>
  
</div>

<div class="col-sm-9 psikotest-result">

</div>
<div class="clearfix"></div>
<br>


<% content_for :bottom_assets do %>
  <style type="text/css">
    .modal-dialog.modal-sm{
      margin: 200px auto;
    }
  </style>
  <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content" style="padding: 10px;text-align: center;">
        
        <br>
        <div class="progress">
          <div class="progress-bar progress-bar-striped active" role="progressbar"
          aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
            Data sedang diproses....
          </div>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $("document").ready(function(){
      $('.bs-example-modal-sm').modal()
      $.ajax({
          url: "<%= request.path %>.js",
          cache: false,
          success: function(html){
            $('.bs-example-modal-sm').modal('hide')            
          }
      });
    });  
  </script>
<% end %>

app/views/siswas/show.html.erb
<%= render 'form' %>