config/routes.rb
Rails.application.routes.draw do

  resources :pembobotans

  resources :minats

  resources :kehidupan_perasaans

  resources :sikap_kerjas

  resources :kecerdasans

  resources :siswas do
    member do
      get 'psikotest'
      get 'hasil'
      get 'pencabangan'
      get 'laporan'
    end

  end

  devise_for :users

  root 'dashboard#index'

    get 'laporan' => 'siswas#laporan'

end

app/models/sikap_kerja.rb
class SikapKerja < ActiveRecord::Base
  self.table_name = 'sikap_kerja'
  validates :inisiatif, :kreatif, :perencanaan, :energi, :konsentrasi, :kecepatan, :ketelitian, :ketekunan, :keuletan, :daya_tahan, :kepemimpinan, :kerjasama, :toleransi_terhadap_stress, :id_csiswa, presence: true, on: :update
  belongs_to :siswa, foreign_key: :id_csiswa, primary_key: :id_csiswa
    NUMBER_OF_FIELD = 13

  def hasil(pencabangan)
  	res = Pembobotan.where(tipe: "Sikap Kerja", pencabangan: pencabangan)
    

	{:inisiatif => res.where(aspek: "Inisiatif").first.bobot, :kreatif => res.where(aspek: "Kreatif").first.bobot, :perencanaan => res.where(aspek: "Perencanaan").first.bobot,
	 :energi => res.where(aspek: "Energi").first.bobot, :konsentrasi => res.where(aspek: "Konsentrasi").first.bobot, :kecepatan => res.where(aspek: "Kecepatan (Tempo)").first.bobot, 
   :ketelitian => res.where(aspek: "Ketelitian").first.bobot, :ketekunan => res.where(aspek: "Ketekunan").first.bobot, :keuletan => res.where(aspek: "Keuletan").first.bobot, 
   :daya_tahan => res.where(aspek: "Daya Tahan").first.bobot, :kepemimpinan => res.where(aspek: "Kepemimpinan").first.bobot, :kerjasama => res.where(aspek: "Kerjasama").first.bobot, :toleransi_terhadap_stress => res.where(aspek: "Toleransi Terhadap Stress").first.bobot}  	
  end

  def pembobotan(min_val, max_val, val)
  	range = min_val..max_val

  	range.each_slice(range.last/4).with_index.with_object({}) { |(a,i),h|
  	  h[a.first..a.last]=i }
  	enum = range.each_slice(range.last/4)
  	
  	enum.each_with_index do |v, i|
  		return i+1 if val.in?(v)
  	end
  end

    def hasil_pembobotan(pencabangan)
  	arr0 = []
  	hasil(pencabangan).values.each do |val| 
  		arr1 = []
  		arr2 = []
  		hasil(pencabangan).values.each{|val2| arr1 << val2.to_f/val.to_f}
  		arr1.each{|val2| arr2 << val2.to_f/arr1.sum}
  		# hasil.values.each{|val2| arr2 << val2.to_f/arr1.sum}
  		
  		arr0 << arr2
  	end

  	arr3 = []
  	arr0.each_with_index do |val, i|
  		x = 0
  		arr0.each_with_index {|val2, i2| x += arr0[i2][i] }
  		arr3 << x/NUMBER_OF_FIELD

  	end
  	
	arr4 = []

  	arr0.each_with_index do |val, i|
  		x = 0
  		arr0.each_with_index {|val2, i2| x += arr0[i2][i] }
  		arr4 << (x/NUMBER_OF_FIELD) / arr3.sum 
  	end
  	arr4
  end

  def nilai(pencabangan)
  	arr = [self.inisiatif, self.kreatif, self.perencanaan, self.energi, self.konsentrasi, self.kecepatan, self.ketelitian, self.ketekunan, self.keuletan, self.daya_tahan, self.kepemimpinan, self.kerjasama, self.toleransi_terhadap_stress]
	 arr2 = []     
    arr_pemb = hasil_pembobotan(pencabangan)

    arr.each_with_index do |val, idx|
      h_normalisasi = (val.to_f / arr.max.to_f)
      arr2 <<  h_normalisasi * arr_pemb[idx]
    end

    arr2.sum > 0 ? ('%.3g' % arr2.sum) : ''
  end


  def ranking(pencabangan)
    arr = []
    arr4.each_with_index do |val, i|
      arr << (hasil_pembobotan(pencabangan)[i] * nilai(pencabangan)[i])
    end
    arr.sum
  end
end

app/controllers/sikap_kerjas_controller.rb
class SikapKerjasController < ApplicationController
  before_action :set_sikap_kerja, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @sikap_kerjas = SikapKerja.all
    respond_with(@sikap_kerjas)
  end

  def show
    respond_with(@sikap_kerja)
  end

  def new
    @sikap_kerja = SikapKerja.new
    respond_with(@sikap_kerja)
  end

  def edit
  end

  def create
    @sikap_kerja = SikapKerja.new(sikap_kerja_params)
    @sikap_kerja.save
    respond_with(@sikap_kerja)
  end

  def update
    if !@sikap_kerja.update!(sikap_kerja_params)
      flash[:notice] = "Data gagal disimpan, periksa kembali inputan."
    end
    redirect_to psikotest_siswa_path(@sikap_kerja.siswa)
  end

  def destroy
    @sikap_kerja.destroy
    respond_with(@sikap_kerja)
  end

  private
    def set_sikap_kerja
      @sikap_kerja = SikapKerja.find(params[:id])
    end

    def sikap_kerja_params
      params.require(:sikap_kerja).permit(:inisiatif, :kreatif, :perencanaan, :energi, :konsentrasi, :kecepatan, :ketelitian, :ketekunan, :keuletan, :daya_tahan, :kepemimpinan, :kerjasama, :toleransi_terhadap_stress)
    end
end

app/helpers/sikap_kerjas_helper.rb
module SikapKerjasHelper
end

app/views/sikap_kerjas/_form.html.erb
<div class="cols-md-12">
<%= form_for(@sikap_kerja) do |f| %>
<table class="table table-bordered table-stripped">
  <tr>
    <th>Inisiatif</th>
    <th>Kreatif</th>
    <th>Perencanaan</th>
    <th>Energi</th>
    
    </tr>
  <tr>
    <td><%= f.number_field :inisiatif %></td>
    <td><%= f.number_field :kreatif %></td>
    <td><%= f.number_field :perencanaan %></td>
    <td><%= f.number_field :energi %></td>
    
    </tr>
  <tr>
    <th>Kecepatan</th>
    <th>Ketelitian</th>
    <th>Ketekunan</th>
    <th>Keuletan</th>
     
  </tr>
  <tr>  
    <td><%= f.number_field :kecepatan %></td>
    <td><%= f.number_field :ketelitian %></td>
    <td><%= f.number_field :ketekunan %></td>
    <td><%= f.number_field :keuletan %></td>
    
  </tr>
  <tr>
    <th>Konsentrasi</th>   
    <th>Daya Tahan</th>
    <th>Kepemimpinan</th>
    <th>Kerjasama</th>
  </tr>
    
  <tr>  
    <td><%= f.number_field :konsentrasi %></td>
    <td><%= f.number_field :daya_tahan %></td>
    <td><%= f.number_field :kepemimpinan %></td>
    <td><%= f.number_field :kerjasama %></td>
  </tr>
  <tr>
    <th colspan="2">Toleransi Terhadap Stress</th>
  </tr>
    
  <tr>  
    <td  colspan="2"><%= f.number_field :toleransi_terhadap_stress %></td>
  </tr>

</table>
<%= f.submit "Proses", class: "btn btn-primary" %>
<% end %>

</div>
<h3>Hasil</h3>
<div class="cols-md-12">
<%= form_for(@sikap_kerja) do |f| %>
<table class="table table-bordered table-stripped">
  <tr>
    <th>Inisiatif</th>
    <th>Kreatif</th>
    <th>Perencanaan</th>
    <th>Energi</th>
    
    </tr>
  <tr>
    <td><%= f.number_field :inisiatif %></td>
    <td><%= f.number_field :kreatif %></td>
    <td><%= f.number_field :perencanaan %></td>
    <td><%= f.number_field :energi %></td>
    
    </tr>
  <tr>
    <th>Kecepatan</th>
    <th>Ketelitian</th>
    <th>Ketekunan</th>
    <th>Keuletan</th>
     
  </tr>
  <tr>  
    <td><%= f.number_field :kecepatan %></td>
    <td><%= f.number_field :ketelitian %></td>
    <td><%= f.number_field :ketekunan %></td>
    <td><%= f.number_field :keuletan %></td>
    
  </tr>
  <tr>
    <th>Konsentrasi</th>   
    <th>Daya Tahan</th>
    <th>Kepemimpinan</th>
    <th>Kerjasama</th>
  </tr>
    
  <tr>  
    <td><%= f.number_field :konsentrasi %></td>
    <td><%= f.number_field :daya_tahan %></td>
    <td><%= f.number_field :kepemimpinan %></td>
    <td><%= f.number_field :kerjasama %></td>
  </tr>
  <tr>
    <th colspan="2">Toleransi Terhadap Stress</th>
  </tr>
    
  <tr>  
    <td  colspan="2"><%= f.number_field :toleransi_terhadap_stress %></td>
  </tr>
    
  <tr>  
    <td><%= f.number_field :toleransi_terhadap_stress %></td>
  </tr>

</table>
<% end %>

</div>

app/views/sikap_kerjas/edit.html.erb
<%= render 'form' %>

app/views/sikap_kerjas/index.html.erb
<h1>Listing sikap_kerjas</h1>

<table>
  <thead>
    <tr>
      <th>Inisiatif</th>
      <th>Kreatif</th>
      <th>Perencanaan</th>
      <th>Energi</th>
      <th>Konsentrasi</th>
      <th>Kecepatan</th>
      <th>Ketelitian</th>
      <th>Ketekunan</th>
      <th>Keuletan</th>
      <th>Daya tahan</th>
      <th>Kepemimpinan</th>
      <th>Kerjasama</th>
      <th>Toleransi terhadap stress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sikap_kerjas.each do |sikap_kerja| %>
      <tr>
        <td><%= sikap_kerja.inisiatif %></td>
        <td><%= sikap_kerja.kreatif %></td>
        <td><%= sikap_kerja.perencanaan %></td>
        <td><%= sikap_kerja.energi %></td>
        <td><%= sikap_kerja.konsentrasi %></td>
        <td><%= sikap_kerja.kecepatan %></td>
        <td><%= sikap_kerja.ketelitian %></td>
        <td><%= sikap_kerja.ketekunan %></td>
        <td><%= sikap_kerja.keuletan %></td>
        <td><%= sikap_kerja.daya_tahan %></td>
        <td><%= sikap_kerja.kepemimpinan %></td>
        <td><%= sikap_kerja.kerjasama %></td>
        <td><%= sikap_kerja.toleransi_terhadap_stress %></td>
        <td><%= link_to 'Show', sikap_kerja %></td>
        <td><%= link_to 'Edit', edit_sikap_kerja_path(sikap_kerja) %></td>
        <td><%= link_to 'Destroy', sikap_kerja, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sikap kerja', new_sikap_kerja_path %>

app/views/sikap_kerjas/new.html.erb
<h1>New sikap_kerja</h1>

<%= render 'form' %>

<%= link_to 'Back', sikap_kerjas_path %>

app/views/sikap_kerjas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inisiatif:</strong>
  <%= @sikap_kerja.inisiatif %>
</p>

<p>
  <strong>Kreatif:</strong>
  <%= @sikap_kerja.kreatif %>
</p>

<p>
  <strong>Perencanaan:</strong>
  <%= @sikap_kerja.perencanaan %>
</p>

<p>
  <strong>Energi:</strong>
  <%= @sikap_kerja.energi %>
</p>

<p>
  <strong>Konsentrasi:</strong>
  <%= @sikap_kerja.konsentrasi %>
</p>

<p>
  <strong>Kecepatan:</strong>
  <%= @sikap_kerja.kecepatan %>
</p>

<p>
  <strong>Ketelitian:</strong>
  <%= @sikap_kerja.ketelitian %>
</p>

<p>
  <strong>Ketekunan:</strong>
  <%= @sikap_kerja.ketekunan %>
</p>

<p>
  <strong>Keuletan:</strong>
  <%= @sikap_kerja.keuletan %>
</p>

<p>
  <strong>Daya tahan:</strong>
  <%= @sikap_kerja.daya_tahan %>
</p>

<p>
  <strong>Kepemimpinan:</strong>
  <%= @sikap_kerja.kepemimpinan %>
</p>

<p>
  <strong>Kerjasama:</strong>
  <%= @sikap_kerja.kerjasama %>
</p>

<p>
  <strong>Toleransi terhadap stress:</strong>
  <%= @sikap_kerja.toleransi_terhadap_stress %>
</p>

<%= link_to 'Edit', edit_sikap_kerja_path(@sikap_kerja) %> |
<%= link_to 'Back', sikap_kerjas_path %>