config/routes.rb
Rails.application.routes.draw do

  resources :pembobotans

  resources :minats

  resources :kehidupan_perasaans

  resources :sikap_kerjas

  resources :kecerdasans

  resources :siswas do
    member do
      get 'psikotest'
      get 'hasil'
      get 'pencabangan'
      get 'laporan'
    end

  end

  devise_for :users

  root 'dashboard#index'

    get 'laporan' => 'siswas#laporan'

end

app/models/kecerdasan.rb
class Kecerdasan < ActiveRecord::Base
  self.table_name = 'kecerdasan'
  validates :pemahaman, :mengingat, :analisa, :konstruktif, :mengolah_angka, :aritmatika, :orientasi_ruang, :verbal, :estimasi, :tehnik_mekanik, :tehnik_elektronik, :wawasan, :id_csiswa, presence: true, on: :update
  belongs_to :siswa, foreign_key: :id_csiswa, primary_key: :id_csiswa
  NUMBER_OF_FIELD = 12

  def hasil(pencabangan)
    # b_pemahaman = if pemahaman <= 103
    #   1
    # elsif pemahaman.in?(104..111)
    #   2
    # elsif pemahaman.in?(112..119)
    #   3
    # elsif pemahaman.in?(120..127)
    #   4
    # elsif pemahaman >= 118
    #   5
    # end

    # b_mengingat = if mengingat <= 99
    #   1
    # elsif mengingat.in?(100..109)
    #   2
    # elsif mengingat.in?(110..118)
    #   3
    # elsif mengingat.in?(119..128)
    #   4
    # elsif mengingat > 128
    #   5
    # end

    # b_analisa = if analisa <= 88
    #   1
    # elsif analisa.in?(89..99)
    #   2
    # elsif analisa.in?(100..109)
    #   3
    # elsif analisa.in?(110..119)
    #   4
    # elsif analisa > 119
    #   5
    # end

    # b_konstruktif = if konstruktif <= 88
    #   1
    # elsif konstruktif.in?(89..101)
    #   2
    # elsif konstruktif.in?(102..113)
    #   3
    # elsif konstruktif.in?(114..126)
    #   4
    # elsif konstruktif > 126
    #   5
    # end

    # b_mengolah_angka = if mengolah_angka <= 82
    #   1
    # elsif mengolah_angka.in?(83..94)
    #   2
    # elsif mengolah_angka.in?(95..106)
    #   3
    # elsif mengolah_angka.in?(107..118)
    #   4
    # elsif mengolah_angka > 118
    #   5
    # end

    # b_aritmatika = if aritmatika <= 82
    #   1
    # elsif aritmatika.in?(83..94)
    #   2
    # elsif aritmatika.in?(95..106)
    #   3
    # elsif aritmatika.in?(107..118)
    #   4
    # elsif aritmatika > 118
    #   5
    # end

    # b_orientasi_ruang = if orientasi_ruang <= 88
    #   1
    # elsif orientasi_ruang.in?(89..101)
    #   2
    # elsif orientasi_ruang.in?(102..113)
    #   3
    # elsif orientasi_ruang.in?(114..126)
    #   4
    # elsif orientasi_ruang > 126
    #   5
    # end

    # b_verbal = if verbal <= 103
    #   1
    # elsif verbal.in?(104..111)
    #   2
    # elsif verbal.in?(112..119)
    #   3
    # elsif verbal.in?(120..127)
    #   4
    # elsif verbal >= 118
    #   5
    # end

    # b_estimasi = if estimasi <= 92
    #   1
    # elsif estimasi.in?(93..98)
    #   2
    # elsif estimasi.in?(99..104)
    #   3
    # elsif estimasi.in?(105..110)
    #   4
    # elsif estimasi > 110
    #   5
    # end

    # b_tehnik_mekanik = if tehnik_mekanik.in?(0..13)
    #   1
    # elsif tehnik_mekanik.in?(14..27)
    #   2
    # elsif tehnik_mekanik.in?(28..41)
    #   3
    # elsif tehnik_mekanik.in?(42..55)
    #   4
    # elsif tehnik_mekanik.in?(56..68)
    #   5
    # end

    # b_tehnik_elektronik = if tehnik_elektronik.in?(0..13)
    #   1
    # elsif tehnik_elektronik.in?(14..27)
    #   2
    # elsif tehnik_elektronik.in?(28..41)
    #   3
    # elsif tehnik_elektronik.in?(42..55)
    #   4
    # elsif tehnik_elektronik.in?(56..68)
    #   5
    # end

    # b_wawasan = if wawasan <= 90
    #   1
    # elsif wawasan.in?(91..100)
    #   2
    # elsif wawasan.in?(101..110)
    #   3
    # elsif wawasan.in?(111..119)
    #   4
    # elsif wawasan > 119
    #   5
    # end
        

    res = Pembobotan.where(tipe: "Kecerdasan", pencabangan: pencabangan)
    
    hash = {
      :pemahaman => res.where(aspek: "Kemampuan Pemahaman").first.bobot, :mengingat => res.where(aspek: "Kemampuan Mengingat").first.bobot, 
      :analisa => res.where(aspek: "Kemampuan Analisa").first.bobot, :konstruktif => res.where(aspek: "Kemampuan Konstruktif").first.bobot,
      :mengolah_angka => res.where(aspek: "Kemampuan Mengolah Angka (Numerik)").first.bobot, :aritmatika => res.where(aspek: "Kemampuan Aritmatika").first.bobot, 
      :orientasi_ruang => res.where(aspek: "Kemampuan Orientasi Ruang/Bidang").first.bobot, :verbal => res.where(aspek: "Kemampuan Verbal (Bahasa)").first.bobot,
      :estimasi => res.where(aspek: "Kemampuan Estimasi").first.bobot, :tehnik_mekanik => res.where(aspek: "Kemampuan Tehnik Mekanik").first.bobot, 
      :tehnik_elektronik => res.where(aspek: "Kemampuan Tehnik Elektro").first.bobot, :wawasan => res.where(aspek: "Kemampuan Wawasan").first.bobot
    }

  end

  def hasil_pembobotan(pencabangan = "INF")
  	arr0 = []
  	hasil(pencabangan).values.each do |val| 
  		arr1 = []
  		arr2 = []
  		hasil(pencabangan).values.each{|val2| arr1 << val2.to_f/val.to_f}
  		arr1.each{|val2| arr2 << val2.to_f/arr1.sum}
  		# hasil.values.each{|val2| arr2 << val2.to_f/arr1.sum}
  		
  		arr0 << arr2
  	end

  	arr3 = []
  	arr0.each_with_index do |val, i|
  		x = 0
  		arr0.each_with_index {|val2, i2| x += arr0[i2][i] }
  		arr3 << x/NUMBER_OF_FIELD

  	end
  	
	arr4 = []

  	arr0.each_with_index do |val, i|
  		x = 0
  		arr0.each_with_index {|val2, i2| x += arr0[i2][i] }
  		arr4 << (x/NUMBER_OF_FIELD) / arr3.sum 
  	end
  	arr4
  end

  def nilai(pencabangan = "INF")
  	arr = [self.pemahaman, self.mengingat, self.analisa, self.konstruktif, self.mengolah_angka, self.aritmatika, self.orientasi_ruang, self.verbal, 
  		self.estimasi, self.tehnik_mekanik, self.tehnik_elektronik, self.wawasan]
  	arr2 = []  		
    arr_pemb = hasil_pembobotan(pencabangan)

  	arr.each_with_index do |val, idx|
      h_normalisasi = (val.to_f / arr.max.to_f)
  		arr2 <<  h_normalisasi * arr_pemb[idx]
  	end
	  
    arr2.sum > 0 ? ('%.3g' % arr2.sum) : ''
  end


  def ranking(pencabangan = "INF")
  	arr = []
  	arr4.each_with_index do |val, i|
  		arr << (hasil_pembobotan(pencabangan)[i] * nilai(pencabangan)[i])
  	end
  	arr.sum
  end

  def ceil2(exp = 0)
   multiplier = 10 ** exp
   ((self * multiplier).ceil).to_f/multiplier.to_f
  end

end

app/controllers/kecerdasans_controller.rb
class KecerdasansController < ApplicationController
  before_action :set_kecerdasan, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @kecerdasans = Kecerdasan.all
    respond_with(@kecerdasans)
  end

  def show
    respond_with(@kecerdasan)
  end

  def new
    @kecerdasan = Kecerdasan.new
    respond_with(@kecerdasan)
  end

  def edit
  end

  def create
    @kecerdasan = Kecerdasan.new(kecerdasan_params)
    @kecerdasan.save
    respond_with(@kecerdasan)
  end

  def update
    if !@kecerdasan.update(kecerdasan_params)
      flash[:notice] = "Data gagal disimpan, periksa kembali inputan."
    end
    redirect_to psikotest_siswa_path(@kecerdasan.siswa)
  end

  def destroy
    @kecerdasan.destroy
    respond_with(@kecerdasan)
  end

  private
    def set_kecerdasan
      @kecerdasan = Kecerdasan.find(params[:id])
    end

    def kecerdasan_params
      params.require(:kecerdasan).permit(:pemahaman, :mengingat, :analisa, :konstruktif, :mengolah_angka, :aritmatika, :orientasi_ruang, :verbal, :estimasi, :tehnik_mekanik, :tehnik_elektronik, :wawasan)
    end
end

app/helpers/kecerdasans_helper.rb
module KecerdasansHelper
end

app/views/kecerdasans/_form.html.erb
<div class="cols-md-12">
<%= form_for(@kecerdasan) do |f| %>
<table class="table table-bordered table-stripped">
  <tr>
    <th>Pemahaman</th>
    <th>Mengingat</th>
    <th>Analisa</th>
    <th>Konstruktif</th>
    </tr>
  <tr>
    <td><%= f.number_field :pemahaman %></td>
    <td><%= f.number_field :mengingat %></td>
    <td><%= f.number_field :analisa %></td>
    <td><%= f.number_field :konstruktif %></td>
    </tr>
  <tr>
  <th>Mengolah Angka</th>
    <th>Aritmatika</th>
    <th>Orientasi Ruang</th>
    <th>Verbal</th>
  </tr>
  <tr>  
  <td><%= f.number_field :mengolah_angka %></td>
    <td><%= f.number_field :aritmatika %></td>
    <td><%= f.number_field :orientasi_ruang %></td>
    <td><%= f.number_field :verbal %></td>
  </tr>
  <tr>
  <th>Estimasi</th>
    <th>Tehnik Mekanik</th>
    <th>Tehnik Elektronik</th>
    <th>Wawasan</th>
  </tr>

    
    
    
  <tr>  
    <td><%= f.number_field :estimasi %></td>
    <td><%= f.number_field :tehnik_mekanik %></td>
    <td><%= f.number_field :tehnik_elektronik %></td>
    <td><%= f.number_field :wawasan %></td>
  </tr>
</table>
<%= f.submit "Proses", class: "btn btn-primary" %>
<% end %>

</div>

<h3>Hasil</h3>
<div class="cols-md-12">
<%= form_for(@kecerdasan) do |f| %>
<table class="table table-bordered table-stripped">
    <tr>
    <th>Pemahaman</th>
    <th>Mengingat</th>
    <th>Analisa</th>
    <th>Konstruktif</th>
    </tr>
  <tr>

    <td><%= range_of_value(@kecerdasan.pemahaman) %></td>
    <td><%= range_of_value(@kecerdasan.mengingat) %></td>
    <td><%= range_of_value(@kecerdasan.analisa) %></td>
    <td><%= range_of_value(@kecerdasan.konstruktif) %></td>
    </tr>
  <tr>
  <th>Mengolah Angka</th>
    <th>Aritmatika</th>
    <th>Orientasi Ruang</th>
    <th>Verbal</th>
  </tr>
  <tr>  
  <td><%= range_of_value(@kecerdasan.mengolah_angka) %></td>
    <td><%= range_of_value(@kecerdasan.aritmatika) %></td>
    <td><%= range_of_value(@kecerdasan.orientasi_ruang) %></td>
    <td><%= range_of_value(@kecerdasan.verbal) %></td>
  </tr>
  <tr>
  <th>Estimasi</th>
    <th>Tehnik Mekanik</th>
    <th>Tehnik Elektronik</th>
    <th>Wawasan</th>
  </tr>

    
    
    
  <tr>  
    <td><%= range_of_value(@kecerdasan.estimasi) %></td>
    <td><%= range_of_value(@kecerdasan.tehnik_mekanik) %></td>
    <td><%= range_of_value(@kecerdasan.tehnik_elektronik) %></td>
    <td><%= range_of_value(@kecerdasan.wawasan) %></td>
  </tr>
</table>

<% end %>

</div>

app/views/kecerdasans/edit.html.erb
<%= render 'form' %>

app/views/kecerdasans/index.html.erb
<h1>Listing kecerdasans</h1>

<table>
  <thead>
    <tr>
      <th>Pemahaman</th>
      <th>Mengingat</th>
      <th>Analisa</th>
      <th>Konstruktif</th>
      <th>Mengolah angka</th>
      <th>Aritmatika</th>
      <th>Orientasi ruang</th>
      <th>Verbal</th>
      <th>Estimasi</th>
      <th>Tehnik mekanik</th>
      <th>Tehnik elektronik</th>
      <th>Wawasan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kecerdasans.each do |kecerdasan| %>
      <tr>
        <td><%= kecerdasan.pemahaman %></td>
        <td><%= kecerdasan.mengingat %></td>
        <td><%= kecerdasan.analisa %></td>
        <td><%= kecerdasan.konstruktif %></td>
        <td><%= kecerdasan.mengolah_angka %></td>
        <td><%= kecerdasan.aritmatika %></td>
        <td><%= kecerdasan.orientasi_ruang %></td>
        <td><%= kecerdasan.verbal %></td>
        <td><%= kecerdasan.estimasi %></td>
        <td><%= kecerdasan.tehnik_mekanik %></td>
        <td><%= kecerdasan.tehnik_elektronik %></td>
        <td><%= kecerdasan.wawasan %></td>
        <td><%= link_to 'Show', kecerdasan %></td>
        <td><%= link_to 'Edit', edit_kecerdasan_path(kecerdasan) %></td>
        <td><%= link_to 'Destroy', kecerdasan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kecerdasan', new_kecerdasan_path %>

app/views/kecerdasans/new.html.erb
<h1>New kecerdasan</h1>

<%= render 'form' %>

<%= link_to 'Back', kecerdasans_path %>

app/views/kecerdasans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pemahaman:</strong>
  <%= @kecerdasan.pemahaman %>
</p>

<p>
  <strong>Mengingat:</strong>
  <%= @kecerdasan.mengingat %>
</p>

<p>
  <strong>Analisa:</strong>
  <%= @kecerdasan.analisa %>
</p>

<p>
  <strong>Konstruktif:</strong>
  <%= @kecerdasan.konstruktif %>
</p>

<p>
  <strong>Mengolah angka:</strong>
  <%= @kecerdasan.mengolah_angka %>
</p>

<p>
  <strong>Aritmatika:</strong>
  <%= @kecerdasan.aritmatika %>
</p>

<p>
  <strong>Orientasi ruang:</strong>
  <%= @kecerdasan.orientasi_ruang %>
</p>

<p>
  <strong>Verbal:</strong>
  <%= @kecerdasan.verbal %>
</p>

<p>
  <strong>Estimasi:</strong>
  <%= @kecerdasan.estimasi %>
</p>

<p>
  <strong>Tehnik mekanik:</strong>
  <%= @kecerdasan.tehnik_mekanik %>
</p>

<p>
  <strong>Tehnik elektronik:</strong>
  <%= @kecerdasan.tehnik_elektronik %>
</p>

<p>
  <strong>Wawasan:</strong>
  <%= @kecerdasan.wawasan %>
</p>

<%= link_to 'Edit', edit_kecerdasan_path(@kecerdasan) %> |
<%= link_to 'Back', kecerdasans_path %>