config/routes.rb
Rails.application.routes.draw do

  resources :pembobotans

  resources :minats

  resources :kehidupan_perasaans

  resources :sikap_kerjas

  resources :kecerdasans

  resources :siswas do
    member do
      get 'psikotest'
      get 'hasil'
      get 'pencabangan'
      get 'laporan'
    end

  end

  devise_for :users

  root 'dashboard#index'

    get 'laporan' => 'siswas#laporan'

end

app/models/minat.rb
class Minat < ActiveRecord::Base
  self.table_name = 'minat'
  validates :alam_terbuka, :seni, :pelayanan_sosial, :klerical, :teknik_mekanik, :hitungan, :kepustakaan, :ilmiah_sain, :id_csiswa, presence: true, on: :update
  belongs_to :siswa, foreign_key: :id_csiswa, primary_key: :id_csiswa
  NUMBER_OF_FIELD = 8

  def hasil(pencabangan)
    res = Pembobotan.where(tipe: "Minat", pencabangan: pencabangan)
    
    hash = {
      :alam_terbuka => res.where(aspek: "Alam Terbuka (Outdoor)").first.bobot, :seni => res.where(aspek: "Seni (Art)").first.bobot, 
      :pelayanan_sosial => res.where("aspek LIKE (?)", "%Pelayanan Sosial%").first.bobot, :klerical => res.where(aspek: "Klerikal (Clerical)").first.bobot ,
      :teknik_mekanik => res.where(aspek: "Teknik Mekanik (Mechanical)").first.bobot, :hitungan => res.where(aspek: "Hitungan (Computional)").first.bobot, 
      :kepustakaan => res.where(aspek: "Kepustakaan (Literary)").first.bobot, :ilmiah_sain => res.where(aspek: "Ilmiah Sain (Science)").first.bobot}
  end

  def hasil_pembobotan(pencabangan)
  	arr0 = []
  	hasil(pencabangan).values.each do |val| 
  		arr1 = []
  		arr2 = []
  		hasil(pencabangan).values.each{|val2| arr1 << val2.to_f/val.to_f}
  		arr1.each{|val2| arr2 << val2.to_f/arr1.sum}
  		# hasil.values.each{|val2| arr2 << val2.to_f/arr1.sum}
  		
  		arr0 << arr2
  	end

  	arr3 = []
  	arr0.each_with_index do |val, i|
  		x = 0
  		arr0.each_with_index {|val2, i2| x += arr0[i2][i] }
  		arr3 << x/NUMBER_OF_FIELD

  	end
  	
	arr4 = []

  	arr0.each_with_index do |val, i|
  		x = 0
  		arr0.each_with_index {|val2, i2| x += arr0[i2][i] }
  		arr4 << (x/NUMBER_OF_FIELD) / arr3.sum 
  	end
  	arr4
  end

  def nilai(pencabangan)
  	arr = [self.alam_terbuka, self.seni, self.pelayanan_sosial, self.klerical, self.teknik_mekanik, self.hitungan, self.kepustakaan, self.ilmiah_sain]
	 arr2 = []     
    arr_pemb = hasil_pembobotan(pencabangan)

    arr.each_with_index do |val, idx|
      h_normalisasi = (val.to_f / arr.max.to_f)
      arr2 <<  h_normalisasi * arr_pemb[idx]
    end
    
    arr2.sum > 0 ? ('%.3g' % arr2.sum) : ''
  end


  def ranking(pencabangan)
  	arr = []
  	arr4.each_with_index do |val, i|
  		arr << (hasil_pembobotan(pencabangan)[i] * nilai(pencabangan)[i])
  	end
  	arr.sum
  end
end

app/controllers/minats_controller.rb
class MinatsController < ApplicationController
  before_action :set_minat, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @minats = Minat.all
    respond_with(@minats)
  end

  def show
    respond_with(@minat)
  end

  def new
    @minat = Minat.new
    respond_with(@minat)
  end

  def edit
  end

  def create
    @minat = Minat.new(minat_params)
    @minat.save
    respond_with(@minat)
  end

  def update
    @minat.update(minat_params)
    respond_with(@minat)
  end

  def destroy
    @minat.destroy
    respond_with(@minat)
  end

  private
    def set_minat
      @minat = Minat.find(params[:id])
    end

    def minat_params
      params.require(:minat).permit(:alam_terbuka, :seni, :pelayanan_sosial, :klerical, :teknik_mekanik, :hitungan, :kepuasan, :kepustakaan, :ilmiah_sain)
    end
end

app/helpers/minats_helper.rb
module MinatsHelper
end

app/views/minats/_form.html.erb
<div class="cols-md-12">
<%= form_for(@minat) do |f| %>
<table class="table table-bordered table-stripped">
  <tr>
    <th>Alam Terbuka</th>
    <th>Seni</th>
    <th>Pelayanan Sosial</th>
    <th>Klerical</th>
    </tr>
  <tr>
    <td><%= f.number_field :alam_terbuka %></td>
    <td><%= f.number_field :seni %></td>
    <td><%= f.number_field :pelayanan_sosial %></td>
    <td><%= f.number_field :klerical %></td>
    </tr>
  <tr>
  <th>Teknik Mekanik</th>
    <th>Hitungan</th>
    <th>Kepustakaan</th>
    <th>Ilmiah Sain</th>
  </tr>
  <tr>
<td><%= f.number_field :teknik_mekanik %></td>
    <td><%= f.number_field :hitungan %></td>
    <td><%= f.number_field :kepustakaan %></td>
    <td><%= f.number_field :ilmiah_sain %></td>
  </tr>
</table>
<%= f.submit "Proses", class: "btn btn-primary" %>
<% end %>

</div>

<h3>Hasil</h3>
<div class="cols-md-12">
<%= form_for(@minat) do |f| %>
<table class="table table-bordered table-stripped">
  <tr>
    <th>Alam Terbuka</th>
    <th>Seni</th>
    <th>Pelayanan Sosial</th>
    <th>Klerical</th>
    </tr>
  <tr>
    <td><%= f.number_field :alam_terbuka %></td>
    <td><%= f.number_field :seni %></td>
    <td><%= f.number_field :pelayanan_sosial %></td>
    <td><%= f.number_field :klerical %></td>
    </tr>
  <tr>
  <th>Teknik Mekanik</th>
    <th>Hitungan</th>
    <th>Kepustakaan</th>
    <th>Ilmiah Sain</th>
  </tr>
  <tr>
<td><%= f.number_field :teknik_mekanik %></td>
    <td><%= f.number_field :hitungan %></td>
    <td><%= f.number_field :kepustakaan %></td>
    <td><%= f.number_field :ilmiah_sain %></td>
  </tr>
</table>
<%= f.submit "Proses", class: "btn btn-primary" %>
<% end %>

</div>

app/views/minats/edit.html.erb
<%= render 'form' %>

app/views/minats/edit.js.erb
<%= j(render 'form') %>

app/views/minats/index.html.erb
<h1>Listing minats</h1>

<table>
  <thead>
    <tr>
      <th>Alam terbuka</th>
      <th>Seni</th>
      <th>Pelayanan sosial</th>
      <th>Klerical</th>
      <th>Teknik mekanik</th>
      <th>Hitungan</th>
      <th>Kepuasan</th>
      <th>Kepustakaan</th>
      <th>Ilmiah sain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @minats.each do |minat| %>
      <tr>
        <td><%= minat.alam_terbuka %></td>
        <td><%= minat.seni %></td>
        <td><%= minat.pelayanan_sosial %></td>
        <td><%= minat.klerical %></td>
        <td><%= minat.teknik_mekanik %></td>
        <td><%= minat.hitungan %></td>
        <td><%= minat.kepuasan %></td>
        <td><%= minat.kepustakaan %></td>
        <td><%= minat.ilmiah_sain %></td>
        <td><%= link_to 'Show', minat %></td>
        <td><%= link_to 'Edit', edit_minat_path(minat) %></td>
        <td><%= link_to 'Destroy', minat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Minat', new_minat_path %>

app/views/minats/new.html.erb
<%= render 'form' %>

app/views/minats/new.js.erb
<%= j(render 'form') %>

app/views/minats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alam terbuka:</strong>
  <%= @minat.alam_terbuka %>
</p>

<p>
  <strong>Seni:</strong>
  <%= @minat.seni %>
</p>

<p>
  <strong>Pelayanan sosial:</strong>
  <%= @minat.pelayanan_sosial %>
</p>

<p>
  <strong>Klerical:</strong>
  <%= @minat.klerical %>
</p>

<p>
  <strong>Teknik mekanik:</strong>
  <%= @minat.teknik_mekanik %>
</p>

<p>
  <strong>Hitungan:</strong>
  <%= @minat.hitungan %>
</p>

<p>
  <strong>Kepuasan:</strong>
  <%= @minat.kepuasan %>
</p>

<p>
  <strong>Kepustakaan:</strong>
  <%= @minat.kepustakaan %>
</p>

<p>
  <strong>Ilmiah sain:</strong>
  <%= @minat.ilmiah_sain %>
</p>

<%= link_to 'Edit', edit_minat_path(@minat) %> |
<%= link_to 'Back', minats_path %>